# ===== Nerdtree settings =====
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let NERDTreeShowHidden = 1
function MyNerdToggle()
  if &filetype == 'nerdtree' || &filetype == ''
    :NERDTreeToggle
  else
    :NERDTreeFind
  endif

  "Refresh automatically
  exe 'silent normal R'
endfunction

nnoremap <silent> <space>b :call MyNerdToggle()<CR>
let g:NERDTreeLimitedSyntax = 1
let g:NERDTreeMapOpenVSplit = 'v'
let g:NERDTreeMapOpenSplit = 's'
let g:NERDTreeMapOpenInTab = 'e'
let g:NERDTreeMapOpenExpl = ''
let g:NERDTreeQuitOnOpen = 1
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
