call dein#load_toml(g:vim_conf_dir.'/editor/lsp.toml', {'lazy': 0})
call dein#load_toml(g:vim_conf_dir.'/editor/cmp.toml', {'lazy': 0})
call dein#load_toml(g:vim_conf_dir.'/editor/finder.toml', {'lazy': 0})
call dein#load_toml(g:vim_conf_dir.'/editor/status.toml', {'lazy': 0})
call dein#load_toml(g:vim_conf_dir.'/editor/theme.toml', {'lazy': 0})
