# ===== Dein plugin manager settings =====
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:python3_host_prog = expand('/usr/local/bin/python3')
let g:ruby_host_prog = '/usr/bin/ruby'

autocmd VimEnter * call dein#call_hook('post_source')
'''
