# ===== Change window's size =====
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
nnoremap <space>t :WinResizerStartResize<CR>
'''

# ===== Display idnent vertically line =====
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_conceallevel  = &conceallevel
let g:indentLine_concealcursor = &concealcursor

nnoremap <silent> <space>it :IndentLinesToggle<CR>
let g:indentLine_color_term = 113
'''

# ===== Comment out =====
[[plugins]]
repo = 'tpope/vim-commentary'

# ===== Language packs =====
[[plugins]]
repo = 'sheerun/vim-polyglot'

# ===== Surround =====
[[plugins]]
repo = 'tpope/vim-surround'

[[plugin]]
repo = 'tpope/vim-repeat'

# ===== To make git even in vim =====
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap [fugitive] <Nop>
map <C-g> [fugitive]
nmap <silent> [fugitive]o :GBrowse<CR>
vmap <silent> [fugitive]o :GBrowse<CR>
nmap <silent> [fugitive]b :Git blame<CR>
'''

[[plugins]]
repo = 'tpope/vim-rhubarb'

# ===== For pane of tmux controller =====
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-t>h  :TmuxNavigateLeft<cr>
nnoremap <silent> <C-t>j  :TmuxNavigateDown<cr>
nnoremap <silent> <C-t>k  :TmuxNavigateUp<cr>
nnoremap <silent> <C-t>l  :TmuxNavigateRight<cr>
nnoremap <silent> <C-t>\\ :TmuxNavigatePrevious<cr>
'''

# ===== Replace =====
[[plugins]]
repo = 'kqito/vim-easy-replace'

# # ===== Github copilot =====
# NOTE: This plugin will map `<Tab>` in insert mode. This will cause conflict with coc's '<Tab>'

# [[plugins]]
# repo = 'github/copilot.vim'

# ===== easymotion =====
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
map  <space>s <Plug>(easymotion-prefix)
map  <space>ss <Plug>(easymotion-bd-f)
nmap <space>ss <Plug>(easymotion-overwin-f)
'''
