# ===== Highlight toml file =====
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = 'all',
    additional_vim_regex_highlighting = false,
    highlight = {
        enable = true,
        disable = {'help'},
    },
}
EOF
'''
