# ===== Change window's size =====

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
nnoremap <space>t :WinResizerStartResize<CR>
'''

# ===== Display idnent vertically line =====
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_conceallevel  = &conceallevel
let g:indentLine_concealcursor = &concealcursor

nnoremap <silent> <space>it :IndentLinesToggle<CR>
let g:indentLine_color_term = 113
'''

# ===== Comment out =====
[[plugins]]
repo = 'tpope/vim-commentary'

# ===== Surround =====
[[plugins]]
repo = 'tpope/vim-surround'

[[plugin]]
repo = 'tpope/vim-repeat'

# ===== To make git even in vim =====
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap [fugitive] <Nop>
map <C-g> [fugitive]
nmap <silent> [fugitive]o :GBrowse<CR>
vmap <silent> [fugitive]o :GBrowse<CR>
nmap <silent> [fugitive]d :Gdiffsplit<CR>
vmap <silent> [fugitive]d :Gdiffsplit<CR>
nmap <silent> [fugitive]b :Git blame<CR>
'''

[[plugins]]
repo = 'tpope/vim-rhubarb'

# ===== For pane of tmux controller =====
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-t>h  :TmuxNavigateLeft<cr>
nnoremap <silent> <C-t>j  :TmuxNavigateDown<cr>
nnoremap <silent> <C-t>k  :TmuxNavigateUp<cr>
nnoremap <silent> <C-t>l  :TmuxNavigateRight<cr>
nnoremap <silent> <C-t>\\ :TmuxNavigatePrevious<cr>
'''

# ===== Replace =====
[[plugins]]
repo = 'kqito/vim-easy-replace'

# # ===== Github copilot =====
# NOTE: This plugin will map `<Tab>` in insert mode. This will cause conflict with coc's '<Tab>'

# [[plugins]]
# repo = 'github/copilot.vim'

# ===== easymotion =====
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
nmap S <Plug>(easymotion-overwin-f)
'''



# ===== easymotion =====
[[plugins]]
repo = 'monaqa/dial.nvim'
hook_add = '''
lua <<EOF
  vim.keymap.set("n", "<C-a>", require("dial.map").inc_normal(), {noremap = true})
  vim.keymap.set("n", "<C-x>", require("dial.map").dec_normal(), {noremap = true})
  vim.keymap.set("v", "<C-a>", require("dial.map").inc_visual(), {noremap = true})
  vim.keymap.set("v", "<C-x>", require("dial.map").dec_visual(), {noremap = true})
  vim.keymap.set("v", "g<C-a>",require("dial.map").inc_gvisual(), {noremap = true})
  vim.keymap.set("v", "g<C-x>",require("dial.map").dec_gvisual(), {noremap = true})

  local augend = require("dial.augend")
  require("dial.config").augends:register_group{
    -- default augends used when no group name is specified
    default = {
      augend.integer.alias.decimal,   -- nonnegative decimal number (0, 1, 2, 3, ...)
      augend.integer.alias.hex,       -- nonnegative hex number  (0x01, 0x1a1f, etc.)
      augend.date.alias["%Y/%m/%d"],  -- date (2022/02/19, etc.)
      augend.constant.alias.bool,    -- boolean value (true <-> false)
    },

    -- augends used when group with name `mygroup` is specified
    mygroup = {
      augend.integer.alias.decimal,
      augend.date.alias["%m/%d/%Y"], -- date (02/19/2022, etc.)
    }
  }

EOF
'''
