# ===== Status line =====
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
" use powerline-font
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline#extensions#tabline#enabled = 1

let g:airline_section_b = ''
let g:airline_section_y = ''
let g:airline_section_z = ''

if !exists('g:airline_symbols')
let g:airline_symbols = {}
endif
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
" let g:airline_theme='angr'
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
let g:airline#extensions#tabline#enabled = 0 " Integrate for
'''
